trigger:
  branches:
    include:
      - main

variables:
  # Variables de entorno
  ACR_NAME: "myappdevopsgrupo5b" # Colocar el nombre de tu ACR
  IMAGE_NAME: "myappgrupo5-nginx-s6b" # Colocar el Nombre de Imagen
  SERVICE_CONNECTION_NAME: "myappsgrupo5-devops-s6-b" # Colocar nombre del Service Connection ubicado en Docker Registry-- Azure Container Registry

jobs:
  - job: BuildAndPush
    pool:
      vmImage: "ubuntu-latest"
    steps:
      - script: |
          echo "Autenticándose en Azure Container Registry..."
          echo "YGHXT1F6tPK/gQdmkNZHJ86J2gEY6gTP2OKS8YwVt7+ACRCUM6Ib" | docker login myappdevopsgrupo5b.azurecr.io -u myappdevopsgrupo5b --password-stdin
        displayName: "Autenticación en ACR"

      - task: Docker@2
        inputs:
          command: "buildAndPush"
          containerRegistry: "$(SERVICE_CONNECTION_NAME)"
          repository: "$(ACR_NAME).azurecr.io/$(IMAGE_NAME)"
          dockerfile: "**/Dockerfile"
          tags: |
            latest
        displayName: "Build and Push Docker Image"
